[tool.poetry]
name = "badwing"
version = "0.1.0"
description = ""
authors = ["Kurtis Fields <kurtisfields@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9, <3.10"
arcade = "^2.6.2"
#arcade = {git = "https://github.com/pythonarcade/arcade.git", rev = "development"}
click = "^8.0.1"
PyGLM = "^2.4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
