# Size of the window
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
SCREEN_TITLE = 'BadWing'

# Player forces
PLAYER_MOVE_FORCE = 700
PLAYER_JUMP_IMPULSE = 600
PLAYER_PUNCH_IMPULSE = 600

# Kinematic Constants
# Movement speed of player, in pixels per frame
PLAYER_MOVEMENT_SPEED = 500
#PLAYER_MOVEMENT_SPEED = 5
PLAYER_JUMP_SPEED = 750
#PLAYER_JUMP_SPEED = 500
#PLAYER_GRAVITY = (0.0, -981.0)

# How close we get to the edge before scrolling
VIEWPORT_MARGIN = 100

TILE_WIDTH = 128
TILE_SCALING = 1
COIN_SCALING = 0.5
SPRITE_PIXEL_SIZE = 128
GRID_PIXEL_SIZE = (SPRITE_PIXEL_SIZE * TILE_SCALING)

# How many pixels to keep as a minimum margin between the character
# and the edge of the screen.
LEFT_VIEWPORT_MARGIN = 250
RIGHT_VIEWPORT_MARGIN = 250
BOTTOM_VIEWPORT_MARGIN = 100
TOP_VIEWPORT_MARGIN = 100
