#PLAYER_MOVEMENT_SPEED = 500
PLAYER_MOVEMENT_SPEED = 5.0
PLAYER_JUMP_SPEED = 500
#PLAYER_JUMP_SPEED = 15.0

# How many pixels to keep as a minimum margin between the character
# and the edge of the screen.
LEFT_VIEWPORT_MARGIN = 250
RIGHT_VIEWPORT_MARGIN = 250
BOTTOM_VIEWPORT_MARGIN = 100
TOP_VIEWPORT_MARGIN = 100
